### ISSUE TITLE
App crash during using Facebook

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#12]
**Describe the bug**

App crash occurs and message pop-up.

**To Reproduce**

- Browse with Facebook app

**Expected behavior**

**Screenshots**
![1579836196176](https://user-images.githubusercontent.com/8052474/73042759-baa31f80-3ea5-11ea-8863-70378eddd075.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by woohyeok-choi** [comment]
From v 0.9.3, ABC Logger includes Firebase' crashlytics. This may be helpful for a true reason of this bug.

**Comment by woohyeok-choi** [comment]
I found several problems potentially related to this bug.
1) For collection of Bluetooth, some bluetooth device does not have any name, leading to null pointer exception.
2) For collection of call log and messages, there are a case that does not have a number (but I don't know why).

These two issues will be corrected in v 0.9.4.
