### ISSUE TITLE
Required auto-dismiss of Survey notification

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#17]
**Is your feature request related to a problem? Please describe.**

Survey notification always showed even after (1) the survey was closed by timeout setting and (2) the survey was answered by user.

**Describe the solution you'd like**

Auto-dismiss feature is required.
After the corresponding survey cannot be editted by user, the noti should be closed.

**Describe alternatives you've considered**

**Additional context**

![1580291341945](https://user-images.githubusercontent.com/8052474/73346525-57f8bc00-42c9-11ea-894d-54555b260194.jpg)
![Screenshot_20200129-174629_ABC Logger](https://user-images.githubusercontent.com/8052474/73346560-69da5f00-42c9-11ea-9cf4-0e4f6c44a921.jpg)

**Comment by woohyeok-choi** [comment]
1) Add autoCancel option that allow a user to cancel a notification by clicking it in a panel.
2) Add a timeout option that automatically dismisses a notification after a certain duration only for a survey having a timeout policy like DISABLED.
