### ISSUE TITLE
Survey time range bug

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#18]
**Describe the bug**

The range of survey time set incorrectly.
I intend the notification should be alarm between 10am and 10pm, but the notification give me notification at 22:54.

**To Reproduce**

**Expected behavior**

The notifications should be alarm between 10am and 10pm.

**Screenshots**

![Screenshot_20200129-225648_ABC Logger](https://user-images.githubusercontent.com/8052474/73363047-4f18e200-42eb-11ea-847c-cb10df71b31a.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by woohyeok-choi** [comment]
It is resolved in a v0.9.5-b
