### ISSUE TITLE
The size of notification of Foreground service is slightly bigger than the others.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#19]
**Is your feature request related to a problem? Please describe.**

The vertical size of foreground service noti is bigger than others.

**Describe the solution you'd like**

Need to be smaller.

**Describe alternatives you've considered**

**Additional context**

![Screenshot_20200130-111512_One UI Home](https://user-images.githubusercontent.com/8052474/73414442-3bed2d00-4352-11ea-8fb2-ab9198763817.jpg)

**Comment by woohyeok-choi** [comment]
Rollback to default size of notification
