### ISSUE TITLE
App crash while using Polar H10

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#21]
**Describe the bug**

Polar H10's config activity restarts when I frequently turn on and off the UI button.

**To Reproduce**

1. Input the sensor address at the corresponding textbox( on the detailed config of Polar H10 activity).
2. Turn on the sensor button and check the sensor is Connected.
3. Turn off the button.
4. Save the config and turn on the sensor button on the previous Config page.
5. Check the sensor periodically updates the ECG value.
6. Take off the sensor (in order to intend that the sensor powers off.)
7. Turn off the button and click the detailed config activity of Polar H10.
8. Frequently turn on and off the sensor button.
9. App crash occurs.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by woohyeok-choi** [comment]
This is due to a problem of Polar API. However, I can show an error to user (without crash).
