### ISSUE TITLE
Delayed survey activity loading showes unintended text color.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#22]
**Is your feature request related to a problem? Please describe.**

After I loaded the survey page through clicking the ESM noti and wait the next noti, the color of pre-loaded survey keep showing blue, which means that it can be answered.
I cannot save the answer when clicked the survey (it is normal and intended result)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![Screenshot_20200130-171715_ABC Logger](https://user-images.githubusercontent.com/8052474/73453333-222e0300-43af-11ea-9021-0903fb8fc801.jpg)

![Screenshot_20200130-181003_ABC Logger](https://user-images.githubusercontent.com/8052474/73453354-2ce89800-43af-11ea-99b9-ea3c0384242a.jpg)

![Screenshot_20200130-181021_ABC Logger](https://user-images.githubusercontent.com/8052474/73453370-3a058700-43af-11ea-84d1-0cc15f42f9b1.jpg)

**Comment by woohyeok-choi** [comment]
You mean, once open ESM response screen (or activity) by clicking a notification and wait for a while until timeout, then you cannot answer the opened ESM even if still it seems like available to answer (i.e., blue and bold), right?

If then, it is an intended behavior. It is difficult to update UI in real time (i.e., counting timeout and update UI...)

**Comment by woohyeok-choi** [comment]
If I misunderstand this, please come to my office :)
