### ISSUE TITLE
Show response rate of survey to each user

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#23]
**Is your feature request related to a problem? Please describe.**

The users usually experience survey notifications, but some users may have less motivation to answer the surveys.
I want to encourage users by showing the response rate (the current state) of the survey.
A clear digit type feedback of the current state (response rate) can evaluate the users themselves.
The self-reflection effect can also be helpful to encourage users.

When users saw the low score of response rate, they may felt that 'I need to do better. I want a better score. I will not pass the next notifications.'

**Describe the solution you'd like**

Here, the response rate means that the number of answered surveys over the total number of notified surveys. If the user answered 10 surveys among the 16 notifications, the response rate should be 62.5%. 
Users need to check their response rates frequently.
I think that the survey list activity, which is the first page for the logged in users, is the best choice to show the response rate.
How about the top-most place under the menu bar?

**Describe alternatives you've considered**

**Additional context**

**Comment by woohyeok-choi** [comment]
Will be added in v0.9.6
