### ISSUE TITLE
Do you intend not to show the RR-interval value from Polar H10 to users?

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#24]
**Is your feature request related to a problem? Please describe.**

I found that the source code of the polar h10 collector measures the rrs (RR-interval value) as an independent entity.

https://github.com/woohyeok-choi/ABC-Logger/blob/master/app/src/main/kotlin/kaist/iclab/abclogger/collector/externalsensor/polar/PolarH10Collector.kt

However, the test UI only shows the heart-rate and ECG value, not rrs.

Am I right that the ABC Logger actually logs the rrs value either?

**Describe the solution you'd like**

I think we do not need to change the UI, but the rrs info is important.
I am ok if the DB contains the rrs info as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by woohyeok-choi** [comment]
I forgot showing RR. It will be added in v0.9.6
