### ISSUE TITLE
(Key log) One of Note10+ users cannot grant Accessibility service permission.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#28]
**Describe the bug**

When the user who uses Galaxy Note 10+ wants to turn on the Accessibility service, the app shows warning message and cannot grant the permission.

**To Reproduce**

Click "Touch" collector of Config tab.
Click to turn on the Acessibility service.
See error.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Galaxy Note 10+
Android 10

**Additional context**

**Comment by woohyeok-choi** [comment]
After updating Android OS version, it worked.
