### ISSUE TITLE
(Sync) UI of the app has not been loaded for a long time.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#47]
**Describe the bug**

After turn on the app, the app starts log-in the Google ID.
The main page of ABC Logger (Survey list) cannot be loaded at the time.
Also, the Config page cannot be loaded.

**To Reproduce**

This is not a quite clear path of reproducing.
Since many of LTE-sync users report this issue, I guess that the simultaneous sync and load can lead this problem.
We have already solved that the survey item disappearing issue even before timeout. That problem may cause by the sync. I think that the sync can interfere UI loading after solving the timeout issue.

**Expected behavior**

**Screenshots**

![Screenshot_20200228-101547_ABC Logger](https://user-images.githubusercontent.com/8052474/75513578-9accc180-5a38-11ea-89fa-29878b56f225.jpg)
![Screenshot_20200228-101550_ABC Logger](https://user-images.githubusercontent.com/8052474/75513587-a02a0c00-5a38-11ea-8f16-27506c324184.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

samsung-SM-G950N-9
samsung-SM-G960N-10

**Additional context**

**Comment by soowon-kang** [comment]
![Resized_CYMERA_20200228_144402](https://user-images.githubusercontent.com/8052474/75514290-7e318900-5a3a-11ea-850d-a986bb5bc09e.jpeg)

**Comment by woohyeok-choi** [comment]
Releated to Isssue #48

**Comment by soowon-kang** [comment]
fixed in 0.9.9-iota
