### ISSUE TITLE
(Key log) The timestamp of Key log table should be modified.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#54]
**Describe the bug**
In key log, timestamp is not "UnixTimestamp".

The current version's timestamp in Key log table gets AccessibilityService.eventTime.
-- https://stackoverflow.com/questions/55030433/android-accessibilityservice-geteventtime-time-format

This means that the timestamp cannot be easily replaced.

The following links are some helpful information to debug this issue.
-- https://developer.android.com/reference/android/view/accessibility/AccessibilityEvent#getEventTime()
-- https://developer.android.com/reference/android/os/SystemClock?hl=en
-- https://github.com/zelatore/KeyLogger/blob/update_keytracker/app/src/main/java/kr/ac/kaist/jypark/keylogger/KeyTrackingService.kt

**Expected behavior**
I think that System.currentTimemillis() would be better for this,
but I'm afraid that the exact event time (key touch) can be slightly wrong.
I'm not sure that the exact event time and the currentTimeMillis always show the same result. 

**Screenshots**

![image](https://user-images.githubusercontent.com/8052474/77497359-783f9400-6e90-11ea-9661-913d635d0641.png)

**Comment by cheonsol-lee** [comment]
It needs a timestamp to set standards like UnixTimeStamp.

**Comment by soowon-kang** [comment]
Change the timestamp format as UNIX timestamp.
