### ISSUE TITLE
(Notification) The time at "isPosted=false" is wrong.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#56]
**Describe the bug**

The notification collector should collect the time when each post turned on/off.
The "isPosted" value is related to the above statement.
In the "onNotificationRemoved ()" function, the "isPosted" value set as false.
However, "val postTime = sbn.postTime" is not working correctly at this time.
We intended the collector should log the time of the post off, but it logged the time of the post on again.
Thus, there exist all pairs of isPosted=true/false and the same timestamp (=the time of the post on).

**To Reproduce**

**Expected behavior**

We should know the time of each post off.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by soowon-kang** [comment]
The original "isPosted=false" is fixed, but a related and unexpected issue occurs now.
We cannot match the notification pairs (isPosted=true and false), which means that which notification was removed from the notification bar even if we found one.
I think we need a UUID for each notification.

A notification may not be removed when the app showed it continuously.
To explain this, I assume that Slack received 3 msg from another colleague.
The notifications of slack may occur three times, but removing them occurred only once when the user clicked the msg.

**Comment by woohyeok-choi** [comment]
Actually, this is not a problem. As  you know, each notification has its ID (like, NotificationManager.notify(int, Notification) ), and the previous notification goes away (but, actually not removed; just updated) if the app deliveres new notification with the same ID. Maybe we can add a field saying notification ID and TAG

**Comment by woohyeok-choi** [comment]
Fixed
