### ISSUE TITLE
(Data traffic) The collected data sometimes show the negative values, which is wrong.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#60]
**Describe the bug**

In the database, we collected about a 2-month long dataset.
When I checked the data-traffic table, there are several negative values of sending/receiving bytes of network communication.

**To Reproduce**

**Expected behavior**

Cannot understand how the data bytes become negative for both sending/receiving cases.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by soowon-kang** [comment]
@woohyeok-choi 
I found some error records only in the alpha version data. (No weird record is founded in the beta~epsilon version.)
You can find them by using the below code.

```javascript
db.datum.find({
    $and: [{
            datumType: { $exists: true }
        }, {
            subject: { $exists: true }
        }, {
            datumType : "DATA_TRAFFIC"
        }, {
            "value.fromTime": {$gt: 1600439766323}
        }, {
        $or: [{
            "value.rxBytes": {$lt: 0}
        }, {
            "value.txBytes": {$lt: 0}
        }, {
            "value.mobileRxBytes": {$lt: 0}
        }, {
            "value.mobileTxBytes": {$lt: 0}
        }]
        }
    ]
}).sort({
    datumType: -1,
    subject: -1,
    timestamp: -1
}).limit(10)
```

**Comment by woohyeok-choi** [comment]
@suwon419 I found negative values are reported in a version of 0.9.9-delta.
