### ISSUE TITLE
(AppUsage) The timestamp of App usage event seems to be wrong.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#62]
**Describe the bug**

We expect that the results of the collected app_usage_event contain the timestamp when each event occurred.
However, 0.9.9-c version contains the timestamp when each event collected.
I think that we need to use Event.getTimestamp() method instead of System.currentTimeMillis().

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Here is a helpful reference. [LINK](https://developer.android.com/reference/kotlin/android/app/usage/UsageEvents.Event
)

**Comment by woohyeok-choi** [comment]
Fixed
