### ISSUE TITLE
(AppUsage) The type column's STANDBY_BUCKET_CHANGED needs more information

### ISSUE THREAD

**Issue by hansoolee18** [woohyeok-choi/ABC-Logger#63]
**Describe the bug**

type column에 **"STANDBY_BUCKET_CHANGED"**라는 **categorical value**가 있는데,
이번년도에 새로 보이는 value입니다. API level 28부터 추가된 것으로 알고 있고,

하지만, 현재는 "STANDBY_BUCKET_CHANGED"라고만 떠있어, 
이것만으로는 현재 해당 앱이 어떤 상태인지 알기는 부족합니다.
만약 포함이 필요하다면 현재 상태를 나타내주는 하위 단계 중 하나 값도 log되야 할 것 같습니다.
하위단계는 "Active", "Working Set", "Rare", "Never"로 나뉩니다.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by woohyeok-choi** [comment]
Added Stand-by-bucket event.
