### ISSUE TITLE
(Internal sensor data: light sensor & proximity sensor)'s frequency is not proper

### ISSUE THREAD

**Issue by hansoolee18** [woohyeok-choi/ABC-Logger#64]
**Describe the bug**

App상 어쩔 수 없는 버그라 수정이 될지 안될지 모르겠지만,
일단은 보고차 남겨 둡니다. 
프로그래밍상 internal sensor (light sensor 및 proximity sensor)의 경우 3초 단위로 주기적으로 들어오는 것으로 알고 있습니다. 하지만, 오차를 고려하여 보아도 실제 들어오는 interval을 확인해보았을때
3초에 한번 들어온 것은 전체의  9.62%이고, 최대 40초에 한 번 들어온 경우도 있었습니다.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by woohyeok-choi** [comment]
This is because internally (maybe) adaptive sampling is applied.
Official docs also say defined sampling rates may not be applied.
