### ISSUE TITLE
(Bluetooth Data) device_name column has many missing value and total data amount is too small

### ISSUE THREAD

**Issue by hansoolee18** [woohyeok-choi/ABC-Logger#65]
**Describe the bug**

1. Bluetooth data's total amount is too small

Bluetooth Data의 data 는 10 분의 sampling rate로 들어오는 것으로 알 고 있습니다.
또한, 하기 세 가지 조건을 충족해야 log되는 것으로 알고 있습니다.

- Bluetooth가 꺼진 경우 데이터가 10 min마다 들어오지 않고,
- Bluetooth의 변경이 없는 경우 10 min마다 한번씩 데이터가 들어옴
- Bluetooth의 변경이 있는 경우 10 min이 지나지 않아도 데이터가 들어옴

Bluetooth가 켜졌을때만 데이터가 들어오는 것을 감안하더라도 4주 동안 150개 row에 해당되는 데이터가 들어오는 것은 너무 작다고 생각되어 한번 코드에 대한 확인이 필요합니다. 또한, 상황을 몰라 데이터만 가지고는 판단이 힘들어 테스팅을 해봐야할 듯 합니다.

2. Bluetooth data's "device_name" column has many missing value

Bluetooth data의 address column의 특정 장치의 주소값이 들어오는 경우에도 
device_name의 column이 공백인 경우가 매우 많습니다. 만약 장치의 명칭이 없는 경우에는 unknown으로 들어오는데,
공백인 경우에는 무엇인가 오류로 보입니다. 확인이 필요합니다.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by woohyeok-choi** [comment]
Fixed
