### ISSUE TITLE
(Physical activity) Timestamp is not periodically logged

### ISSUE THREAD

**Issue by hansoolee18** [woohyeok-choi/ABC-Logger#66]
**Describe the bug**

App 상 문제라 수정될지 안될지 모르겠지만,
프로그래밍상 15s라 설정되있는데, 15초 또는 16초로 들어올때도 있지만, 
짧게는 8초, 7초, 20초, 28초, 31초, 길게는 16분, 20분 단위로 들어올때도 있어 
확인이 필요합니다. 

시간대로 들어온다면 앱이 꺼지거나 스마트폰 전원의 셧다운으로 볼 수도 있지만,
분 단위로 늦게 들어오는 경우라 코드상 문제가 있나 하여 리포트하였습니다.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by woohyeok-choi** [comment]
Periodicity cannot be achieved due to adaptive sampling
