### ISSUE TITLE
(Notification) Tag must not be null

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#69]
**Describe the bug**

Cannot collect any data.
Error msgs occur repeatedly.

**To Reproduce**
1. Turn on the "Notification" collector (Status -> ON)
2. Error occurs in one minute. (See screenshot)

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/8052474/96532978-f568a580-12c7-11eb-8826-9ea21d8deca2.png)

**Smartphone (please complete the following information):**
 - Device: Note9, SM-N960N
 - OS: ANDROID10
 - App ver: 0.9.9-alpha

**Comment by woohyeok-choi** [comment]
It will be fixed

**Comment by soowon-kang** [comment]
problem solved.
