### ISSUE TITLE
(CallLog / Message) Permission Denial

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#70]
**Describe the bug**

Cannot collect any log

**To Reproduce**
1. Turn on the collector (Status ON)
2. Error occurs in any minute (less than 5 min)

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/8052474/96534053-f69ad200-12c9-11eb-8c57-7a1ab5b745d4.png)

![image](https://user-images.githubusercontent.com/8052474/96534037-f13d8780-12c9-11eb-8eea-d693b2606aa2.png)

**Smartphone (please complete the following information):**
 - Device: Note9
 - OS: Android 10
 - App ver: 0.9.9-alpha

**Additional context**

**Comment by soowon-kang** [comment]
The errors repeatedly (about 15-min period) occur even if turned off the Call Log and Message collectors.

**Comment by woohyeok-choi** [comment]
It is may be due to missing permissions.  I'll added READ_SMS, and READ_CALL_LOG permission

**Comment by soowon-kang** [comment]
problem solved.
