### ISSUE TITLE
(Collector) Error message occurs when click "Availability" in Collectors which do not require additional availability setting

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#71]
**Describe the bug**

If click "Availability" of a collector that has already set as "Available",
an instant message occurs. (see screenshot)

**To Reproduce**
1. Click the "Availability" button in a collector (e.g., Call Log)

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/8052474/96534451-b38d2e80-12ca-11eb-874d-564a6f3cb298.png)

**Smartphone (please complete the following information):**
 - Device: Note9
 - OS: Android10
 - Version 0.9.9-alpha

**Additional context**

**Comment by woohyeok-choi** [comment]
Does this problem occurs in any collector?

**Comment by soowon-kang** [comment]
It seems the message occurs only in a few collectors that do not need to change any "availability"

**Comment by woohyeok-choi** [comment]
It will be fixed in the next release (0.9.9-gamma)

**Comment by soowon-kang** [comment]
confirmed in epsilon version
