### ISSUE TITLE
(Config) Data size on Disk showed very higher value than the actual size of the app.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#73]
**Describe the bug**

It seems that the value of Data size on Disk increases too fast (about 100MB/min).

I turned on every collector (except for polar, survey, call log, message, notification, wifi, location) that works well for now,
and the number of records from each collector increases normally.

I checked the actual size of the app in "저장공간" of ABC Logger,
and it showed a very small size (데이터: 2MB) for now (about 20 minutes collection).

**Smartphone (please complete the following information):**
 - Device: Note9
 - OS: Android10
 - App version: 0.9.9-alpha

**Additional context**

**Comment by woohyeok-choi** [comment]
Let me know whether this is due to just representation error or not.

**Comment by soowon-kang** [comment]
In-app data size value is a bit different from the android system's value (37MB vs 38MB).
But, I think it seems good enough.
