### ISSUE TITLE
(App Usage/Typing Speed/Notification) Be able to turn on the collectors without Availability checked.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#75]
**Describe the bug**

Some of the collectors have to change the Availability setting in the config activity of each collector.
However, I can turn on the Status of app usage, typing speed, and notification collectors without changing the Availability setting.
Unfortunately, those collectors cannot gather any data :(

**To Reproduce**
1. Go to Config activity.
2. Click one of those collectors that need to change Availability.
3. Turn on Status.
4. It seems that I can successfully turn on the collector but it cannot gather any data from the smartphone.

**Expected behavior**

I think that we have to prevent turning on the collector at the Unavailable status.

**Screenshots**

![image](https://user-images.githubusercontent.com/8052474/96859855-fc94dc80-149c-11eb-8740-dae708103681.png)
![image](https://user-images.githubusercontent.com/8052474/96859866-ff8fcd00-149c-11eb-8f10-d457a28f81b2.png)
![image](https://user-images.githubusercontent.com/8052474/96859875-01f22700-149d-11eb-8931-b04834ca038b.png)

**Smartphone (please complete the following information):**
 - Device: Note 9
 - OS: Android-10

**Comment by woohyeok-choi** [comment]
You're right; a current operation is not a intedented one. It wil be fixed in the next release.
