### ISSUE TITLE
(Media) no data collected.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#77]
**Describe the bug**

There is no data in DB.

**To Reproduce**
1. Capture screenshot, Use camera apps
2. But no data collected.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Note9
 - OS: Android10
 - Version delta

**Additional context**

**Comment by woohyeok-choi** [comment]
This is because the time column of images or videos is formatted as a seconds, not milliseconds. It will be fixed at the next version

**Comment by soowon-kang** [comment]
confirmed in epsilon version.
