### ISSUE TITLE
(Message/CallLog@DB) The timestamp in DB is weird.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#79]
**Describe the bug**

Message's timestamp in DB represents the Year 2038.
Maybe, there are some misunderstandings when checking the #77 issue.

**Screenshots**

**Additional context**

```javascript
db.datum.find({
    $and: [{
            datumType: { $exists: true }
        }, {
            subject: { $exists: true }
        }, {
            datumType : "MESSAGE"
        }, {
            "subject.groupName": "099e-tndnjs"
        },
        {
            "timestamp": {$gt: 1600439766323}
        }, 
    ]
}).sort({
    datumType: -1,
    subject: -1,
    timestamp: -1
}).limit(10)
```

**Comment by woohyeok-choi** [comment]
Can you check this issue occurs in CallLog or Media? Because Message, CallLog, and Media collectors have same collection mechanics; so, if there is any problem amount those collectors, rest of them may have same problems.

**Comment by soowon-kang** [comment]
Media works well but the same issue is founded in CallLog.

**Comment by soowon-kang** [comment]
will be fixed in zeta
